name: Build Native Application

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Setup Windows SDK
      uses: microsoft/setup-msbuild@v1.3.1
        
    - name: Install MAUI Workload
      run: |
        dotnet workload install maui-windows --ignore-failed-sources --skip-manifest-update
      
    - name: Restore dependencies
      working-directory: ./TeReoLocalizer
      run: dotnet restore TeReoLocalizer.sln
      
    - name: Run publish script
      shell: cmd
      working-directory: ./TeReoLocalizer/TeReoLocalizer
      run: |
        set "AUTOMATION_MODE=1"
        call publish.bat

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: TeReoLocalizer
        path: ./TeReoLocalizer/TeReoLocalizer/bin/Release/net8.0-windows10.0.19041.0/win10-x64/dist/TeReoLocalizer.zip